#ifndef DEVICES_SLI_H
#define DEVICES_SLI_H

#define SLI_TYPE_SERIAL 1
#define SLI_TYPE_DISK_DRIVE 2
#define SLI_TYPE_FLASH_DRIVE 3
#define SLI_TYPE_KEYBOARD 4
#define SLI_TYPE_MOUSE 5
#define SLI_TYPE_CONTROLLER 6
#define SLI_TYPE_DISPLAY_MONITOR 7
#define SLI_TYPE_SOUND_CARD 8
#define SLI_TYPE_NETWORK_CARD 9
#define SLI_TYPE_GRAPHICAL_CARD 10

#define SLI_VENDOR_STANDARD 1


#endif